import { Product, Category, ProductVariant, Coupon } from "../lib/types";

// Mock Categories updated to match Header.tsx
export const mockCategories: Category[] = [
  {
    id: "cat_womens_perfume",
    slug: "womens-perfume",
    name_ar: "عطور نسائية",
    description_ar: "تشكيلة ساحرة من العطور النسائية الفاخرة",
    image_url: "/store/creamy_banner_perfumes_1777682428754.png",
    sort_order: 1,
  },
  {
    id: "cat_mens_perfume",
    slug: "mens-perfume",
    name_ar: "عطور رجالية",
    description_ar: "عطور رجالية تعكس القوة والفخامة الأبدية",
    image_url: "/store/creamy_banner_skincare_1777682451392.png",
    sort_order: 2,
  },
  {
    id: "cat_skincare",
    slug: "skincare",
    name_ar: "العناية بالبشرة",
    description_ar: "مستحضرات عناية فاخرة لبشرة مشرقة وشبابية",
    image_url: "/store/creamy_gift_boxes_1777682551722.png",
    sort_order: 3,
  },
  {
    id: "cat_makeup",
    slug: "makeup",
    name_ar: "المكياج",
    description_ar: "أرقى خطوط المكياج لإبراز جمالك الفريد",
    image_url: "/store/creamy_banner_perfumes_1777682428754.png",
    sort_order: 4,
  },
  {
    id: "cat_luxury_gifts",
    slug: "luxury-gifts",
    name_ar: "هدايا فاخرة",
    description_ar: "مجموعات هدايا حصرية لمن تحبين",
    image_url: "/store/creamy_gift_boxes_1777682551722.png",
    sort_order: 5,
  },
];

export const mockVariants: Record<string, ProductVariant[]> = {
  prod_1: [
    { id: "var_1_50ml", name_ar: "50 مل", price_delta: 0, stock: 10, sort_order: 1 },
    { id: "var_1_100ml", name_ar: "100 مل", price_delta: 250, stock: 5, sort_order: 2 },
  ],
  prod_2: [{ id: "var_2_std", name_ar: "قياسي", price_delta: 0, stock: 20, sort_order: 1 }],
};

// Mock Products matching the luxury categories
export const mockProducts: Product[] = [
  {
    id: "prod_1",
    slug: "sahara-royal-oud",
    name_ar: "سحر العود الملكي",
    description_ar:
      "عطر فاخر يجمع بين رائحة العود الأصيل ومزيج من الزهور الساحرة ليعطيك إطلالة لا تُنسى.",
    ingredients_ar: "العود، خشب الصندل، الورد الطائفي، المسك، العنبر",
    brand: "سحر",
    price: 950,
    compare_price: 1200,
    stock: 15,
    category_id: "cat_mens_perfume",
    rating: 4.9,
    review_count: 128,
    is_featured: true,
    is_new: false,
    is_active: true,
    product_images: [
      {
        id: "img_1_1",
        url: "/store/creamy_banner_perfumes_1777682428754.png",
        alt_text: "Sahara Royal Oud Bottle",
        sort_order: 1,
      },
      {
        id: "img_1_2",
        url: "/store/creamy_banner_skincare_1777682451392.png",
        alt_text: "Sahara Royal Oud Lifestyle",
        sort_order: 2,
      },
    ],
    product_variants: mockVariants["prod_1"],
    categories: { slug: "mens-perfume", name_ar: "عطور رجالية" },
  },
  {
    id: "prod_2",
    slug: "golden-vanilla",
    name_ar: "الفانيلا الذهبية",
    description_ar:
      "نفحات من الفانيليا الدافئة الممزوجة بالكراميل لتجربة عطرية ناعمة وأنثوية، صُممت لتأسرك.",
    ingredients_ar: "فانيلا، كراميل، زهور بيضاء، ياسمين",
    brand: "سحر",
    price: 450,
    compare_price: null,
    stock: 20,
    category_id: "cat_womens_perfume",
    rating: 4.8,
    review_count: 85,
    is_featured: true,
    is_new: true,
    is_active: true,
    product_images: [
      {
        id: "img_2_1",
        url: "/store/creamy_gift_boxes_1777682551722.png",
        alt_text: "Golden Vanilla Product",
        sort_order: 1,
      },
    ],
    product_variants: mockVariants["prod_2"],
    categories: { slug: "womens-perfume", name_ar: "عطور نسائية" },
  },
  {
    id: "prod_4",
    slug: "luxury-gift-set-1",
    name_ar: "مجموعة هدايا سحر الحصرية",
    description_ar:
      "مجموعة متكاملة تحتوي على عطر سحر الملكي وبخور وعود حصري في صندوق فاخر يعكس الفخامة.",
    ingredients_ar: "مختلط",
    brand: "سحر",
    price: 1500,
    compare_price: 1800,
    stock: 8,
    category_id: "cat_luxury_gifts",
    rating: 5.0,
    review_count: 14,
    is_featured: true,
    is_new: true,
    is_active: true,
    product_images: [
      {
        id: "img_4_1",
        url: "/store/creamy_banner_skincare_1777682451392.png",
        alt_text: "Gift Set",
        sort_order: 1,
      },
    ],
    product_variants: [
      { id: "var_4_1", name_ar: "صندوق كامل", price_delta: 0, stock: 8, sort_order: 1 },
    ],
    categories: { slug: "luxury-gifts", name_ar: "هدايا فاخرة" },
  },
  {
    id: "prod_5",
    slug: "sahara-serum-absolute",
    name_ar: "سيروم سحر المطلق",
    description_ar:
      "تجديد فوري للبشرة بخلاصة الذهب عيار ٢٤ وحمض الهيالورونيك، لبشرة تشع نضارة وترطيباً عميقاً.",
    ingredients_ar: "حمض الهيالورونيك، خلاصة الذهب الطبيعي، فيتامين سي",
    brand: "إكسير",
    price: 320,
    compare_price: null,
    stock: 35,
    category_id: "cat_skincare",
    rating: 4.7,
    review_count: 211,
    is_featured: false,
    is_new: true,
    is_active: true,
    product_images: [
      {
        id: "img_5_1",
        url: "/store/creamy_banner_perfumes_1777682428754.png",
        alt_text: "Serum Absolute",
        sort_order: 1,
      },
    ],
    product_variants: [
      { id: "var_5_1", name_ar: "30 مل", price_delta: 0, stock: 35, sort_order: 1 },
    ],
    categories: { slug: "skincare", name_ar: "العناية بالبشرة" },
  },
  {
    id: "prod_6",
    slug: "velvet-matte-lipstick",
    name_ar: "أحمر شفاه مطفي مخملي",
    description_ar:
      'أحمر الشفاه المخملي بدرجة "الأحمر الداكن" الفاخر، ثبات يدوم طويلاً ولون غني من الطبقة الأولى.',
    ingredients_ar: "شمع النحل الطبيعي، زيوت مرطبة، ألوان معدنية نقية",
    brand: "سحر",
    price: 185,
    compare_price: 220,
    stock: 50,
    category_id: "cat_makeup",
    rating: 4.9,
    review_count: 432,
    is_featured: true,
    is_new: false,
    is_active: true,
    product_images: [
      {
        id: "img_6_1",
        url: "/store/creamy_gift_boxes_1777682551722.png",
        alt_text: "Velvet Lipstick",
        sort_order: 1,
      },
    ],
    product_variants: [
      { id: "var_6_1", name_ar: "درجة 99", price_delta: 0, stock: 50, sort_order: 1 },
    ],
    categories: { slug: "makeup", name_ar: "المكياج" },
  },
  {
    id: "prod_7",
    slug: "midnight-rose-perfume",
    name_ar: "ورد منتصف الليل",
    description_ar: "عطر زهري غامض وجذاب مستوحى من ورود الليل، يمنحك أنوثة طاغية.",
    ingredients_ar: "ورد، باتشولي، مسك أبيض",
    brand: "سحر",
    price: 380,
    compare_price: 450,
    stock: 12,
    category_id: "cat_womens_perfume",
    rating: 4.7,
    review_count: 56,
    is_featured: true,
    is_new: false,
    is_active: true,
    product_images: [
      {
        id: "img_7_1",
        url: "/store/creamy_banner_perfumes_1777682428754.png",
        alt_text: "Midnight Rose",
        sort_order: 1,
      },
    ],
    product_variants: [
      { id: "var_7_1", name_ar: "100 مل", price_delta: 0, stock: 12, sort_order: 1 },
    ],
    categories: { slug: "womens-perfume", name_ar: "عطور نسائية" },
  },
  {
    id: "prod_8",
    slug: "arabian-knight-cologne",
    name_ar: "عطر الفارس العربي",
    description_ar: "رجولة لا تقاوم مع مزيج الأخشاب والتوابل الشرقية الحارة.",
    ingredients_ar: "خشب الأرز، زعفران، هيل، تبغ",
    brand: "سحر",
    price: 420,
    compare_price: null,
    stock: 25,
    category_id: "cat_mens_perfume",
    rating: 4.8,
    review_count: 90,
    is_featured: false,
    is_new: true,
    is_active: true,
    product_images: [
      {
        id: "img_8_1",
        url: "/store/creamy_banner_skincare_1777682451392.png",
        alt_text: "Arabian Knight",
        sort_order: 1,
      },
    ],
    product_variants: [
      { id: "var_8_1", name_ar: "100 مل", price_delta: 0, stock: 25, sort_order: 1 },
    ],
    categories: { slug: "mens-perfume", name_ar: "عطور رجالية" },
  },
  {
    id: "prod_9",
    slug: "glow-toner-water",
    name_ar: "تونر النضارة والترطيب",
    description_ar: "ماء مقطر بالورد لتوازن البشرة وإغلاق المسام بلطف، مثالي للاستخدام اليومي.",
    ingredients_ar: "ماء الورد، فيتامين E، الصبار",
    brand: "نقاء",
    price: 95,
    compare_price: 120,
    stock: 60,
    category_id: "cat_skincare",
    rating: 4.5,
    review_count: 310,
    is_featured: false,
    is_new: false,
    is_active: true,
    product_images: [
      {
        id: "img_9_1",
        url: "/store/creamy_gift_boxes_1777682551722.png",
        alt_text: "Glow Toner",
        sort_order: 1,
      },
    ],
    product_variants: [
      { id: "var_9_1", name_ar: "200 مل", price_delta: 0, stock: 60, sort_order: 1 },
    ],
    categories: { slug: "skincare", name_ar: "العناية بالبشرة" },
  },
  {
    id: "prod_10",
    slug: "luxury-bridal-gift",
    name_ar: "صندوق العروس الملكي",
    description_ar: "تشكيلة متكاملة للعروس من أجود العطور والبخور والمخمريات.",
    ingredients_ar: "عطورات، بخور، عود",
    brand: "سحر",
    price: 3500,
    compare_price: 4000,
    stock: 3,
    category_id: "cat_luxury_gifts",
    rating: 5.0,
    review_count: 5,
    is_featured: true,
    is_new: true,
    is_active: true,
    product_images: [
      {
        id: "img_10_1",
        url: "/store/creamy_banner_perfumes_1777682428754.png",
        alt_text: "Bridal Gift",
        sort_order: 1,
      },
    ],
    product_variants: [
      { id: "var_10_1", name_ar: "الإصدار المحدود", price_delta: 0, stock: 3, sort_order: 1 },
    ],
    categories: { slug: "luxury-gifts", name_ar: "هدايا فاخرة" },
  },
  {
    id: "prod_11",
    slug: "flawless-foundation",
    name_ar: "كريم أساس فلوليس",
    description_ar: "تغطية كاملة مع لمسة طبيعية ومشرقة تدوم طوال اليوم دون تكتل.",
    ingredients_ar: "بدون زيوت، حماية من الشمس SPF20",
    brand: "تألق",
    price: 210,
    compare_price: null,
    stock: 45,
    category_id: "cat_makeup",
    rating: 4.6,
    review_count: 154,
    is_featured: false,
    is_new: false,
    is_active: true,
    product_images: [
      {
        id: "img_11_1",
        url: "/store/creamy_gift_boxes_1777682551722.png",
        alt_text: "Foundation",
        sort_order: 1,
      },
    ],
    product_variants: [
      { id: "var_11_1", name_ar: "بيج طبيعي", price_delta: 0, stock: 45, sort_order: 1 },
    ],
    categories: { slug: "makeup", name_ar: "المكياج" },
  },
  {
    id: "prod_12",
    slug: "jasmine-breeze",
    name_ar: "نسيم الياسمين",
    description_ar: "رائحة الياسمين النقي تضفي إحساساً بالنظافة والراحة.",
    ingredients_ar: "ياسمين أبيض، حمضيات خفيفة",
    brand: "سحر",
    price: 290,
    compare_price: null,
    stock: 18,
    category_id: "cat_womens_perfume",
    rating: 4.4,
    review_count: 42,
    is_featured: false,
    is_new: false,
    is_active: true,
    product_images: [
      {
        id: "img_12_1",
        url: "/store/creamy_banner_skincare_1777682451392.png",
        alt_text: "Jasmine Breeze",
        sort_order: 1,
      },
    ],
    product_variants: [
      { id: "var_12_1", name_ar: "50 مل", price_delta: 0, stock: 18, sort_order: 1 },
    ],
    categories: { slug: "womens-perfume", name_ar: "عطور نسائية" },
  },
  {
    id: "prod_13",
    slug: "blue-ocean-men",
    name_ar: "أوشن بلو الرجالي",
    description_ar: "عطر صيفي بامتياز ومنعش مستوحى من أعماق المحيط.",
    ingredients_ar: "نسيم البحر، برغموت، نعناع",
    brand: "سحر",
    price: 310,
    compare_price: 350,
    stock: 30,
    category_id: "cat_mens_perfume",
    rating: 4.6,
    review_count: 112,
    is_featured: false,
    is_new: false,
    is_active: true,
    product_images: [
      {
        id: "img_13_1",
        url: "/store/creamy_banner_perfumes_1777682428754.png",
        alt_text: "Blue Ocean",
        sort_order: 1,
      },
    ],
    product_variants: [
      { id: "var_13_1", name_ar: "100 مل", price_delta: 0, stock: 30, sort_order: 1 },
    ],
    categories: { slug: "mens-perfume", name_ar: "عطور رجالية" },
  },
  {
    id: "prod_14",
    slug: "anti-aging-night-cream",
    name_ar: "كريم الليل المجدد",
    description_ar: "يعمل أثناء النوم على تجديد الخلايا ومحاربة التجاعيد الدقيقة.",
    ingredients_ar: "ريتينول، كولاجين، زبدة الشيا",
    brand: "إكسير",
    price: 450,
    compare_price: null,
    stock: 15,
    category_id: "cat_skincare",
    rating: 4.9,
    review_count: 88,
    is_featured: true,
    is_new: true,
    is_active: true,
    product_images: [
      {
        id: "img_14_1",
        url: "/store/creamy_gift_boxes_1777682551722.png",
        alt_text: "Night Cream",
        sort_order: 1,
      },
    ],
    product_variants: [
      { id: "var_14_1", name_ar: "50 مل", price_delta: 0, stock: 15, sort_order: 1 },
    ],
    categories: { slug: "skincare", name_ar: "العناية بالبشرة" },
  },
  {
    id: "prod_15",
    slug: "volume-mascara",
    name_ar: "مسكرة الكثافة القصوى",
    description_ar: "نظرة درامية مع رموش أطول وأكثر كثافة بدون تكتلات.",
    ingredients_ar: "فيتامين B5",
    brand: "تألق",
    price: 120,
    compare_price: 150,
    stock: 80,
    category_id: "cat_makeup",
    rating: 4.7,
    review_count: 220,
    is_featured: false,
    is_new: false,
    is_active: true,
    product_images: [
      {
        id: "img_15_1",
        url: "/store/creamy_banner_skincare_1777682451392.png",
        alt_text: "Mascara",
        sort_order: 1,
      },
    ],
    product_variants: [
      { id: "var_15_1", name_ar: "أسود فاحم", price_delta: 0, stock: 80, sort_order: 1 },
    ],
    categories: { slug: "makeup", name_ar: "المكياج" },
  },
  {
    id: "prod_16",
    slug: "oud-wood-incense",
    name_ar: "عود خشب فاخر",
    description_ar: "أجود أنواع العود الطبيعي لتبخير منزلك ومناسباتك الخاصة.",
    ingredients_ar: "خشب عود طبيعي",
    brand: "سحر",
    price: 850,
    compare_price: 1000,
    stock: 22,
    category_id: "cat_luxury_gifts",
    rating: 4.9,
    review_count: 67,
    is_featured: false,
    is_new: false,
    is_active: true,
    product_images: [
      {
        id: "img_16_1",
        url: "/store/creamy_gift_boxes_1777682551722.png",
        alt_text: "Oud Wood",
        sort_order: 1,
      },
    ],
    product_variants: [
      { id: "var_16_1", name_ar: "1 تولة", price_delta: 0, stock: 22, sort_order: 1 },
    ],
    categories: { slug: "luxury-gifts", name_ar: "هدايا فاخرة" },
  },
];

export const mockCoupons: Coupon[] = [
  {
    id: "coup_1",
    code: "SAHARA10",
    type: "percentage",
    value: 10,
    min_cart_value: 0,
    is_active: true,
  },
  {
    id: "coup_2",
    code: "LUXURY50",
    type: "fixed",
    value: 50,
    min_cart_value: 500,
    is_active: true,
  },
];

export const mockShippingZones = [
  { id: "zone_1", name_ar: "الرياض", cost: 0, estimated_days: "خلال 24 ساعة" },
  { id: "zone_2", name_ar: "جدة والدمام", cost: 25, estimated_days: "1-3 أيام عمل" },
  { id: "zone_3", name_ar: "باقي مدن المملكة", cost: 35, estimated_days: "3-5 أيام عمل" },
];

export const mockOrders: any[] = []; // In-memory mock for session
